# ------------------------------------------------------------------------------
#
# Run this script to output a list of Agility Blue PowerShell commands.
#
# ------------------------------------------------------------------------------

Get-AgilityBlueCommand

# ------------------------------------------------------------------------------
# Example Output:
# ------------------------------------------------------------------------------
# Add-BillingEntry
# Add-BillingNarrativeType
# Add-BillingType
# Add-Client
# Add-Comment
# Add-Contact
# Add-CustomObject
# Add-EmailMessage
# Add-EmailMessageAttachments
# Add-EmailMessageContacts
# Add-EmailTemplate
# Add-Form
# Add-GridState
# Add-IgnoredFile
# Add-Integration
# Add-LinkedRelativityWorkspace
# Add-Matter
# Add-MediaLogEntry
# Add-MediaType
# Add-Object
# Add-Project
# Add-Setting
# Add-SubscribersToTask
# Add-TagsToProject
# Add-Task
# Add-TaskEmailMessage
# Add-Volume
# Get-AgilityBlueCommand
# Get-BillingEntries
# Get-BillingEntry
# Get-BillingNarrativeType
# Get-BillingNarrativeTypes
# Get-BillingType
# Get-BillingTypes
# Get-Client
# Get-ClientBillingProfile
# Get-Clients
# Get-Comment
# Get-Comments
# Get-Contact
# Get-Contacts
# Get-CustomObject
# Get-CustomObjects
# Get-DataTypes
# Get-EmailMessage
# Get-EmailMessageAttachment
# Get-EmailMessageAttachments
# Get-EmailMessageContact
# Get-EmailMessageContacts
# Get-EmailMessages
# Get-EmailTemplate
# Get-EmailTemplates
# Get-FieldPropertyTypes
# Get-FileReference
# Get-FileReferences
# Get-Form
# Get-Forms
# Get-FormTypes
# Get-GridState
# Get-GridStates
# Get-IgnoredFile
# Get-IgnoredFiles
# Get-Integration
# Get-Integrations
# Get-LinkedRelativityWorkspace
# Get-LinkedRelativityWorkspaces
# Get-Matter
# Get-MatterBillingProfile
# Get-Matters
# Get-MediaLogEntries
# Get-MediaLogEntry
# Get-MediaType
# Get-MediaTypes
# Get-NotificationRuleObjectTypes
# Get-Object
# Get-Objects
# Get-Project
# Get-ProjectBillingProfile
# Get-Projects
# Get-ProjectSourceTypes
# Get-ProjectTypes
# Get-Setting
# Get-Settings
# Get-Task
# Get-TaskComment
# Get-TaskCommentTypes
# Get-TaskEmailMessage
# Get-TaskFormFields
# Get-TaskQualityCheckStatusTypes
# Get-Tasks
# Get-TaskStatusTypes
# Get-Volume
# Get-Volumes
# Get-WorkspaceUser
# Get-WorkspaceUsers
# Remove-BillingEntry
# Remove-BillingNarrativeType
# Remove-BillingType
# Remove-Client
# Remove-Comment
# Remove-Contact
# Remove-CustomObject
# Remove-EmailMessage
# Remove-EmailMessageAttachment
# Remove-EmailMessageContact
# Remove-EmailTemplate
# Remove-FileReference
# Remove-Form
# Remove-GridState
# Remove-IgnoredFile
# Remove-Integration
# Remove-LinkedRelativityWorkspace
# Remove-Matter
# Remove-MediaLogEntry
# Remove-MediaType
# Remove-Object
# Remove-Project
# Remove-Setting
# Remove-TagsFromProject
# Remove-Task
# Remove-TaskEmailMessage
# Remove-Volume
# Send-EmailMessage
# Set-AssignTask
# Set-BillingEntry
# Set-BillingNarrativeType
# Set-BillingType
# Set-CancelProject
# Set-Client
# Set-Comment
# Set-CompleteTask
# Set-Contact
# Set-CustomObject
# Set-EmailMessage
# Set-EmailTemplate
# Set-FileReference
# Set-Form
# Set-GridState
# Set-IgnoredFile
# Set-Integration
# Set-LinkedRelativityWorkspace
# Set-Matter
# Set-MediaLogEntry
# Set-MediaType
# Set-Object
# Set-Project
# Set-ReopenTask
# Set-Setting
# Set-Task
# Set-TaskQualityCheckStatus
# Set-TaskStatus
# Set-UnCancelProject
# Set-Volume
# Set-WorkspaceUserNotificationsEnabled
# ------------------------------------------------------------------------------